
name: Bug report
description: For problems and errors
labels: bug
assignees: JackDunnCodes
body:
- type: input
  id: which
  attributes:
    label: Which file/project is this issue related to?
    description: "There's multiple projects in this repo. I need to know what one you're using"
    placeholder: "e.g. moreuniqid.php, onlinephp-autologin.user.js"
  validations:
    required: true
- type: textarea
  id: describe
  attributes:
    label: Describe the bug
    description: "A clear and concise description of what the bug is."
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: Reproduction steps
    description: "How can I reproduce the bug? Provide a step-by-step guide on how you got the problem."
    value: "1."
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: What did you expect to happen?
    placeholder: "I expected the code to..."
  validations:
    required: true
- type: textarea
  id: actual
  attributes:
    label: What actually happened?
    description: Include outputs verbatim. Include screenshots if relevant.
  validations:
    required: true
- type: textarea
  id: device
  attributes:
    label: What device did this happen on?
    value: |
      Desktop, mobile, or server:
      Which OS and version:
      Which browser or software:
      Which version of the browser/software:
  validations:
    required: true
- type: textarea
  id: context
  attributes:
    label: Anything else we should know?
    description: Any additional context that may be useful or relevant that you haven't covered above.
